name: Deploy to Droplet

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.DROPLET_IP }} >> ~/.ssh/known_hosts

      - name: Deploy via SSH
        run: |
          ssh root@${{ secrets.DROPLET_IP }} << 'EOF'
            cd portfolio
            git pull origin main
            docker stop website
            docker rm website
            docker build -t website .
            docker run -p 8080:8080 --name website -d website
            docker system prune -f
          EOF
